//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EstudioJuridico
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Estudio_JuridicoEntities : DbContext
    {
        public Estudio_JuridicoEntities()
            : base("name=Estudio_JuridicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spFichaPredialPropietarioscrear(Nullable<int> id_ficha, Nullable<int> id_propietario, string anotacion)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var id_propietarioParameter = id_propietario.HasValue ?
                new ObjectParameter("id_propietario", id_propietario) :
                new ObjectParameter("id_propietario", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialPropietarioscrear", id_fichaParameter, id_propietarioParameter, anotacionParameter);
        }
    
        public virtual int spFichaPredialPropietariosmodificar(Nullable<int> id_ficha_perdial_propietario, Nullable<int> id_propietario, string anotacion)
        {
            var id_ficha_perdial_propietarioParameter = id_ficha_perdial_propietario.HasValue ?
                new ObjectParameter("id_ficha_perdial_propietario", id_ficha_perdial_propietario) :
                new ObjectParameter("id_ficha_perdial_propietario", typeof(int));
    
            var id_propietarioParameter = id_propietario.HasValue ?
                new ObjectParameter("id_propietario", id_propietario) :
                new ObjectParameter("id_propietario", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialPropietariosmodificar", id_ficha_perdial_propietarioParameter, id_propietarioParameter, anotacionParameter);
        }
    
        public virtual int spMatriculaDerivadascrear(Nullable<int> id_ficha, string matricula, Nullable<bool> estado, string pk_predio, string ubicar)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var pk_predioParameter = pk_predio != null ?
                new ObjectParameter("pk_predio", pk_predio) :
                new ObjectParameter("pk_predio", typeof(string));
    
            var ubicarParameter = ubicar != null ?
                new ObjectParameter("ubicar", ubicar) :
                new ObjectParameter("ubicar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatriculaDerivadascrear", id_fichaParameter, matriculaParameter, estadoParameter, pk_predioParameter, ubicarParameter);
        }
    
        public virtual int spMatriculaDerivadasmodificar(Nullable<int> id_matricula_derivada, string matricula, Nullable<bool> estado, string pk_predio, string ubicar)
        {
            var id_matricula_derivadaParameter = id_matricula_derivada.HasValue ?
                new ObjectParameter("id_matricula_derivada", id_matricula_derivada) :
                new ObjectParameter("id_matricula_derivada", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var pk_predioParameter = pk_predio != null ?
                new ObjectParameter("pk_predio", pk_predio) :
                new ObjectParameter("pk_predio", typeof(string));
    
            var ubicarParameter = ubicar != null ?
                new ObjectParameter("ubicar", ubicar) :
                new ObjectParameter("ubicar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatriculaDerivadasmodificar", id_matricula_derivadaParameter, matriculaParameter, estadoParameter, pk_predioParameter, ubicarParameter);
        }
    
        public virtual ObjectResult<spMatriculaDerivadasconsultar_Result> spMatriculaDerivadasconsultar(Nullable<int> id_ficha, string matricula, Nullable<bool> estado, string pk_predio, string ubicar)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var pk_predioParameter = pk_predio != null ?
                new ObjectParameter("pk_predio", pk_predio) :
                new ObjectParameter("pk_predio", typeof(string));
    
            var ubicarParameter = ubicar != null ?
                new ObjectParameter("ubicar", ubicar) :
                new ObjectParameter("ubicar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMatriculaDerivadasconsultar_Result>("spMatriculaDerivadasconsultar", id_fichaParameter, matriculaParameter, estadoParameter, pk_predioParameter, ubicarParameter);
        }
    
        public virtual int spFichaPredialeseliminar(Nullable<int> id_ficha)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialeseliminar", id_fichaParameter);
        }
    
        public virtual ObjectResult<spFichaPredialesconsultar_Result> spFichaPredialesconsultar(string numero_ficha)
        {
            var numero_fichaParameter = numero_ficha != null ?
                new ObjectParameter("numero_ficha", numero_ficha) :
                new ObjectParameter("numero_ficha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFichaPredialesconsultar_Result>("spFichaPredialesconsultar", numero_fichaParameter);
        }
    
        public virtual ObjectResult<spFichaPredialPropietariosconsultar_Result> spFichaPredialPropietariosconsultar(Nullable<int> id_ficha, Nullable<int> id_propietario, string anotacion, Nullable<int> id_ficha_predial_propietario)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var id_propietarioParameter = id_propietario.HasValue ?
                new ObjectParameter("id_propietario", id_propietario) :
                new ObjectParameter("id_propietario", typeof(int));
    
            var anotacionParameter = anotacion != null ?
                new ObjectParameter("anotacion", anotacion) :
                new ObjectParameter("anotacion", typeof(string));
    
            var id_ficha_predial_propietarioParameter = id_ficha_predial_propietario.HasValue ?
                new ObjectParameter("id_ficha_predial_propietario", id_ficha_predial_propietario) :
                new ObjectParameter("id_ficha_predial_propietario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFichaPredialPropietariosconsultar_Result>("spFichaPredialPropietariosconsultar", id_fichaParameter, id_propietarioParameter, anotacionParameter, id_ficha_predial_propietarioParameter);
        }
    
        public virtual int spMatriculaDerivadaseliminar(Nullable<int> id_ficha)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatriculaDerivadaseliminar", id_fichaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spFichaPredialescrear(string numero_ficha, string folio_matriz, Nullable<bool> estado_folio_matriz, Nullable<System.DateTime> fecha_apertura_folio, Nullable<System.DateTime> fecha_primera_anotacion, Nullable<decimal> area_escritura, Nullable<decimal> area_ovc, Nullable<decimal> area_folio, string ruta_archivo, string razon_diferencia_areas, string antecedentes, string estudio_folio_matriz, string analisis_areas, string anotacion_que_afecte_la_inscripcion, string proteccion_colectiva, string linderos, string instrucciones_visita_campo, string direccion_folio, string quien_elaboro_yaprobo, Nullable<System.DateTime> fecha_control_calidad_juridico, string control_calidad_juridico, string aprobacion_interventoria, Nullable<System.DateTime> fecha_aprobacion)
        {
            var numero_fichaParameter = numero_ficha != null ?
                new ObjectParameter("numero_ficha", numero_ficha) :
                new ObjectParameter("numero_ficha", typeof(string));
    
            var folio_matrizParameter = folio_matriz != null ?
                new ObjectParameter("folio_matriz", folio_matriz) :
                new ObjectParameter("folio_matriz", typeof(string));
    
            var estado_folio_matrizParameter = estado_folio_matriz.HasValue ?
                new ObjectParameter("estado_folio_matriz", estado_folio_matriz) :
                new ObjectParameter("estado_folio_matriz", typeof(bool));
    
            var fecha_apertura_folioParameter = fecha_apertura_folio.HasValue ?
                new ObjectParameter("fecha_apertura_folio", fecha_apertura_folio) :
                new ObjectParameter("fecha_apertura_folio", typeof(System.DateTime));
    
            var fecha_primera_anotacionParameter = fecha_primera_anotacion.HasValue ?
                new ObjectParameter("fecha_primera_anotacion", fecha_primera_anotacion) :
                new ObjectParameter("fecha_primera_anotacion", typeof(System.DateTime));
    
            var area_escrituraParameter = area_escritura.HasValue ?
                new ObjectParameter("area_escritura", area_escritura) :
                new ObjectParameter("area_escritura", typeof(decimal));
    
            var area_ovcParameter = area_ovc.HasValue ?
                new ObjectParameter("area_ovc", area_ovc) :
                new ObjectParameter("area_ovc", typeof(decimal));
    
            var area_folioParameter = area_folio.HasValue ?
                new ObjectParameter("area_folio", area_folio) :
                new ObjectParameter("area_folio", typeof(decimal));
    
            var ruta_archivoParameter = ruta_archivo != null ?
                new ObjectParameter("ruta_archivo", ruta_archivo) :
                new ObjectParameter("ruta_archivo", typeof(string));
    
            var razon_diferencia_areasParameter = razon_diferencia_areas != null ?
                new ObjectParameter("razon_diferencia_areas", razon_diferencia_areas) :
                new ObjectParameter("razon_diferencia_areas", typeof(string));
    
            var antecedentesParameter = antecedentes != null ?
                new ObjectParameter("antecedentes", antecedentes) :
                new ObjectParameter("antecedentes", typeof(string));
    
            var estudio_folio_matrizParameter = estudio_folio_matriz != null ?
                new ObjectParameter("estudio_folio_matriz", estudio_folio_matriz) :
                new ObjectParameter("estudio_folio_matriz", typeof(string));
    
            var analisis_areasParameter = analisis_areas != null ?
                new ObjectParameter("analisis_areas", analisis_areas) :
                new ObjectParameter("analisis_areas", typeof(string));
    
            var anotacion_que_afecte_la_inscripcionParameter = anotacion_que_afecte_la_inscripcion != null ?
                new ObjectParameter("anotacion_que_afecte_la_inscripcion", anotacion_que_afecte_la_inscripcion) :
                new ObjectParameter("anotacion_que_afecte_la_inscripcion", typeof(string));
    
            var proteccion_colectivaParameter = proteccion_colectiva != null ?
                new ObjectParameter("proteccion_colectiva", proteccion_colectiva) :
                new ObjectParameter("proteccion_colectiva", typeof(string));
    
            var linderosParameter = linderos != null ?
                new ObjectParameter("linderos", linderos) :
                new ObjectParameter("linderos", typeof(string));
    
            var instrucciones_visita_campoParameter = instrucciones_visita_campo != null ?
                new ObjectParameter("instrucciones_visita_campo", instrucciones_visita_campo) :
                new ObjectParameter("instrucciones_visita_campo", typeof(string));
    
            var direccion_folioParameter = direccion_folio != null ?
                new ObjectParameter("direccion_folio", direccion_folio) :
                new ObjectParameter("direccion_folio", typeof(string));
    
            var quien_elaboro_yaproboParameter = quien_elaboro_yaprobo != null ?
                new ObjectParameter("quien_elaboro_yaprobo", quien_elaboro_yaprobo) :
                new ObjectParameter("quien_elaboro_yaprobo", typeof(string));
    
            var fecha_control_calidad_juridicoParameter = fecha_control_calidad_juridico.HasValue ?
                new ObjectParameter("fecha_control_calidad_juridico", fecha_control_calidad_juridico) :
                new ObjectParameter("fecha_control_calidad_juridico", typeof(System.DateTime));
    
            var control_calidad_juridicoParameter = control_calidad_juridico != null ?
                new ObjectParameter("control_calidad_juridico", control_calidad_juridico) :
                new ObjectParameter("control_calidad_juridico", typeof(string));
    
            var aprobacion_interventoriaParameter = aprobacion_interventoria != null ?
                new ObjectParameter("aprobacion_interventoria", aprobacion_interventoria) :
                new ObjectParameter("aprobacion_interventoria", typeof(string));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spFichaPredialescrear", numero_fichaParameter, folio_matrizParameter, estado_folio_matrizParameter, fecha_apertura_folioParameter, fecha_primera_anotacionParameter, area_escrituraParameter, area_ovcParameter, area_folioParameter, ruta_archivoParameter, razon_diferencia_areasParameter, antecedentesParameter, estudio_folio_matrizParameter, analisis_areasParameter, anotacion_que_afecte_la_inscripcionParameter, proteccion_colectivaParameter, linderosParameter, instrucciones_visita_campoParameter, direccion_folioParameter, quien_elaboro_yaproboParameter, fecha_control_calidad_juridicoParameter, control_calidad_juridicoParameter, aprobacion_interventoriaParameter, fecha_aprobacionParameter);
        }
    
        public virtual int spFichaPredialesmodificar(Nullable<int> id_ficha, string folio_matriz, Nullable<bool> estado_folio_matriz, Nullable<System.DateTime> fecha_apertura_folio, Nullable<System.DateTime> fecha_primera_anotacion, Nullable<decimal> area_escritura, Nullable<decimal> area_ovc, Nullable<decimal> area_folio, string ruta_archivo, string razon_diferencia_areas, string antecedentes, string estudio_folio_matriz, string analisis_areas, string anotacion_que_afecta_la_inscripcion, string proteccion_colectiva, string linderos, string instrucciones_visita_campo, string direccion_folio, string quien_elaboro_yaprobo, Nullable<System.DateTime> fecha_control_calidad_juridico, string control_calidad_juridico, string aprobacion_interventoria, Nullable<System.DateTime> fecha_aprobacion)
        {
            var id_fichaParameter = id_ficha.HasValue ?
                new ObjectParameter("id_ficha", id_ficha) :
                new ObjectParameter("id_ficha", typeof(int));
    
            var folio_matrizParameter = folio_matriz != null ?
                new ObjectParameter("folio_matriz", folio_matriz) :
                new ObjectParameter("folio_matriz", typeof(string));
    
            var estado_folio_matrizParameter = estado_folio_matriz.HasValue ?
                new ObjectParameter("estado_folio_matriz", estado_folio_matriz) :
                new ObjectParameter("estado_folio_matriz", typeof(bool));
    
            var fecha_apertura_folioParameter = fecha_apertura_folio.HasValue ?
                new ObjectParameter("fecha_apertura_folio", fecha_apertura_folio) :
                new ObjectParameter("fecha_apertura_folio", typeof(System.DateTime));
    
            var fecha_primera_anotacionParameter = fecha_primera_anotacion.HasValue ?
                new ObjectParameter("fecha_primera_anotacion", fecha_primera_anotacion) :
                new ObjectParameter("fecha_primera_anotacion", typeof(System.DateTime));
    
            var area_escrituraParameter = area_escritura.HasValue ?
                new ObjectParameter("area_escritura", area_escritura) :
                new ObjectParameter("area_escritura", typeof(decimal));
    
            var area_ovcParameter = area_ovc.HasValue ?
                new ObjectParameter("area_ovc", area_ovc) :
                new ObjectParameter("area_ovc", typeof(decimal));
    
            var area_folioParameter = area_folio.HasValue ?
                new ObjectParameter("area_folio", area_folio) :
                new ObjectParameter("area_folio", typeof(decimal));
    
            var ruta_archivoParameter = ruta_archivo != null ?
                new ObjectParameter("ruta_archivo", ruta_archivo) :
                new ObjectParameter("ruta_archivo", typeof(string));
    
            var razon_diferencia_areasParameter = razon_diferencia_areas != null ?
                new ObjectParameter("razon_diferencia_areas", razon_diferencia_areas) :
                new ObjectParameter("razon_diferencia_areas", typeof(string));
    
            var antecedentesParameter = antecedentes != null ?
                new ObjectParameter("antecedentes", antecedentes) :
                new ObjectParameter("antecedentes", typeof(string));
    
            var estudio_folio_matrizParameter = estudio_folio_matriz != null ?
                new ObjectParameter("estudio_folio_matriz", estudio_folio_matriz) :
                new ObjectParameter("estudio_folio_matriz", typeof(string));
    
            var analisis_areasParameter = analisis_areas != null ?
                new ObjectParameter("analisis_areas", analisis_areas) :
                new ObjectParameter("analisis_areas", typeof(string));
    
            var anotacion_que_afecta_la_inscripcionParameter = anotacion_que_afecta_la_inscripcion != null ?
                new ObjectParameter("anotacion_que_afecta_la_inscripcion", anotacion_que_afecta_la_inscripcion) :
                new ObjectParameter("anotacion_que_afecta_la_inscripcion", typeof(string));
    
            var proteccion_colectivaParameter = proteccion_colectiva != null ?
                new ObjectParameter("proteccion_colectiva", proteccion_colectiva) :
                new ObjectParameter("proteccion_colectiva", typeof(string));
    
            var linderosParameter = linderos != null ?
                new ObjectParameter("linderos", linderos) :
                new ObjectParameter("linderos", typeof(string));
    
            var instrucciones_visita_campoParameter = instrucciones_visita_campo != null ?
                new ObjectParameter("instrucciones_visita_campo", instrucciones_visita_campo) :
                new ObjectParameter("instrucciones_visita_campo", typeof(string));
    
            var direccion_folioParameter = direccion_folio != null ?
                new ObjectParameter("direccion_folio", direccion_folio) :
                new ObjectParameter("direccion_folio", typeof(string));
    
            var quien_elaboro_yaproboParameter = quien_elaboro_yaprobo != null ?
                new ObjectParameter("quien_elaboro_yaprobo", quien_elaboro_yaprobo) :
                new ObjectParameter("quien_elaboro_yaprobo", typeof(string));
    
            var fecha_control_calidad_juridicoParameter = fecha_control_calidad_juridico.HasValue ?
                new ObjectParameter("fecha_control_calidad_juridico", fecha_control_calidad_juridico) :
                new ObjectParameter("fecha_control_calidad_juridico", typeof(System.DateTime));
    
            var control_calidad_juridicoParameter = control_calidad_juridico != null ?
                new ObjectParameter("control_calidad_juridico", control_calidad_juridico) :
                new ObjectParameter("control_calidad_juridico", typeof(string));
    
            var aprobacion_interventoriaParameter = aprobacion_interventoria != null ?
                new ObjectParameter("aprobacion_interventoria", aprobacion_interventoria) :
                new ObjectParameter("aprobacion_interventoria", typeof(string));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFichaPredialesmodificar", id_fichaParameter, folio_matrizParameter, estado_folio_matrizParameter, fecha_apertura_folioParameter, fecha_primera_anotacionParameter, area_escrituraParameter, area_ovcParameter, area_folioParameter, ruta_archivoParameter, razon_diferencia_areasParameter, antecedentesParameter, estudio_folio_matrizParameter, analisis_areasParameter, anotacion_que_afecta_la_inscripcionParameter, proteccion_colectivaParameter, linderosParameter, instrucciones_visita_campoParameter, direccion_folioParameter, quien_elaboro_yaproboParameter, fecha_control_calidad_juridicoParameter, control_calidad_juridicoParameter, aprobacion_interventoriaParameter, fecha_aprobacionParameter);
        }
    }
}
